# Generated by Django 3.2 on 2022-05-30 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='Autores',
        ),
        migrations.AddField(
            model_name='livro',
            name='Autores',
            field=models.ManyToManyField(to='main.Autor'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='editora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.editora'),
        ),
    ]
